services:
  - type: web
    name: nids
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir Flask_App app:app
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true